### ISSUE TITLE
discord-wayland uses old electron version

### ISSUE THREAD

**Issue by tbsteinb** [TheGreatMcPain/TheGreatMcPain-overlay#13]
The version of electron being used for discord-wayland is quite old now. The reason such an old version is in use is likely because electron 17 and later had some changes that would cause discord to crash due to failing to load a module. This left people stumped for a while, but a solution was found in the AUR - https://aur.archlinux.org/packages/discord_arch_electron

Quoting for the final change:
> Following @lcronos advice i modified it a little and it to more usable version for packaging. Change in app.asar.unpacked/app_bootstrap/requireNative.js:
> 
> module.paths = ["/home/" + process.env.USER + "/.config/discord/0.0.18/modules"];
> 
> It works with electron 18, wayland streaming is still broken

It doesn't look like they implemented it in the pkgbuild yet, but this should be applicable here as well. I don't know ebuild scripts well enough yet to implement it, but having a newer version of electron would be nice.

**Comment by TheGreatMcPain** [comment]
Yeah, I based my ebuild off of [this aur pkgbuild](https://aur.archlinux.org/packages/discord_arch_electron_wayland).

I'll see if I can get it working with a newer electron version.

**Comment by TheGreatMcPain** [comment]
As of the current master discord-wayland should be using whatever electron version you have installed.

I've tested it with electron 19 which is available in this overlay.
