### ISSUE TITLE
`media-video/mpv`: failing at configure phase with: meson.build:1561:11: ERROR: Program 'rst2html' not found or not executable

### ISSUE THREAD

**Issue by atchim** [TheGreatMcPain/TheGreatMcPain-overlay#18]
In the configure phase for `mpv`, the build system looks for `rst2html`, which in fact doesn't exist. There is, although, an executable called `rst2html.py` from `dev-python/docutils`.

**Comment by TheGreatMcPain** [comment]
Yes, I'm aware of this.

Just create a symlink for rst2html that points to rst2html.py.

I should probably note that my mpv ebuild is for the experimental [HDR on DRM pull request](https://github.com/mpv-player/mpv/pull/10762).  So, if you are not testing that you probably shouldn't use my ebuild.

**Comment by atchim** [comment]
Ohh, sure! I just maked it. The main reason why I use your repo is due to Liquorix Kernel and  Nerd Fonts.
