### ISSUE TITLE
Error while trying to compile dev-util/electron

### ISSUE THREAD

**Issue by guilherme-coelho** [TheGreatMcPain/TheGreatMcPain-overlay#21]
Hello, I'm trying to emerge Webcord, which has dev-util/electron as a requirement. However, dev-util/electron-24.1.3 has been failing to build and I can't get it to work... could you take a look if a patch is required for it? Here are some of my outputs, by the way, the same error appeared using GCC13 and 12.

The full output is a gigantic log, which I uploaded [here](https://raw.githubusercontent.com/guilherme-coelho/gentoo/main/build.log). The error part is here:

```

[3244/26306] python3.11 ../../build/gn_run_binary.py nasm -DPIC -felf64 -I../../third_party/libvpx/source/config/ -I../../third_party/libvpx/source/config/linux/x64/ -I../../third_party/libvpx/source/libvpx/ -I./ -I../../ -Igen/ -DCHROMIUM -MD obj/third_party/libvpx/libvpx_asm/highbd_sad4d_sse2.o.d -o obj/third_party/libvpx/libvpx_asm/highbd_sad4d_sse2.o ../../third_party/libvpx/source/libvpx/vpx_dsp/x86/highbd_sad4d_sse2.asm
ninja: build stopped: subcommand failed.
 * ERROR: dev-util/electron-24.1.3::thegreatmcpain failed (compile phase):
 *   ninja -v -j12 -l0 -C out/Release v8_context_snapshot_generator failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_compile
 *   environment, line 5177:  Called eninja '-C' 'out/Release' 'v8_context_snapshot_generator'
 *   environment, line 2978:  Called die
 * The specific snippet of code:
 *       "$@" || die -n "${*} failed"
 * 
 * If you need support, post the output of `emerge --info '=dev-util/electron-24.1.3::thegreatmcpain'`,
 * the complete build log and the output of `emerge -pqv '=dev-util/electron-24.1.3::thegreatmcpain'`.
 * The complete build log is located at '/var/tmp/portage/dev-util/electron-24.1.3/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-util/electron-24.1.3/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-util/electron-24.1.3/work/chromium-112.0.5615.165'
 * S: '/var/tmp/portage/dev-util/electron-24.1.3/work/chromium-112.0.5615.165'

```

Some people suggested that creating a patch that includes `cstdint` could solve this issue, however I'm not very used to programming. Could you give me a few pointers so I can try creating this patch? 

Thanks a lot in advance.

**Comment by TheGreatMcPain** [comment]
I've version bumped `dev-util/electron` (added 24.8.2 and 25.8.0).  There's a good chance the `cstdint` fix as been implemented in the new versions.

I must of missed this error since I personally use Clang to compile electron due to chromium.

Please close if the new versions work for you.

**Comment by guilherme-coelho** [comment]
Thank you, it has been fixed!
