### ISSUE TITLE
Unavailable repository 'bobwya'

### ISSUE THREAD

**Issue by mrturcot** [TheGreatMcPain/TheGreatMcPain-overlay#5]
Hello, portage and layman are spitting this out.

`Unavailable repository 'bobwya' referenced by masters entry in '/var/lib/layman/thegreatmcpain/metadata/layout.conf'`

**Comment by TheGreatMcPain** [comment]
You need to also add the `bobwya` repository via `layman`.
```
layman -a bobwya
```
This is because the `app-emulation/wine-staging` ebuilds are based on the ebuilds from the `bobwya` overlay.

**Comment by mrturcot** [comment]
Thank you very much!
