### ISSUE TITLE
osu-lazer fails to install

### ISSUE THREAD

**Issue by RaphaelNeubert** [TheGreatMcPain/TheGreatMcPain-overlay#8]
Hi, i have trouble installing osu-lazer using your ebuild.
I'm not sure whether there is something wrong, maybe i just screwed something up.

emerge osu-lazer outputs the following.
https://dpaste.com/6SXN57GT6
emerge --info:
https://dpaste.com/BPXZJD7RQ

Thanks for any help.

**Comment by TheGreatMcPain** [comment]
It's related to `app-misc/ca-certificates`.

Something changed between `ca-certificates-20210119.3.62` and `ca-certificates-20210119.3.64` which broke `dotnet restore`.

[It's also related to an issue with `nuget` that started back in January](https://github.com/NuGet/Announcements/issues/49)

~~I'll have to look for a workaround.~~ EDIT: [Looks like there's a new dotnet-sdk version with a workaround](https://github.com/NuGet/Announcements/issues/56)

**Comment by TheGreatMcPain** [comment]
Closed via [6628b60](https://github.com/TheGreatMcPain/TheGreatMcPain-overlay/commit/6628b605dc446d3442b49200a1c18c2d44894a0a)

**Comment by TheGreatMcPain** [comment]
Oh shoot, your error message is a bit different from what I was expecting. My bad.

**Comment by TheGreatMcPain** [comment]
@RaphaelNeubert I think your copy of my overlay is a little out-dated. How did you add my overlay?

Pretty sure I fixed [this issue already.](https://github.com/TheGreatMcPain/TheGreatMcPain-overlay/commit/5b5af7a642429d13f1518cd36f53efb45f9efb8d#diff-c192030372fc442be6882082664aa69e71447979a47a2656af4404895aac32fa)

**Comment by RaphaelNeubert** [comment]
I installed it manually and must have screwed something up. I just relized that your overlay is also available with `eselect repository`. I added it this way and now it works. 

Thank you very much.
